# Generated by Django 4.1.3 on 2022-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_followrequest'),
        ('inbox', '0002_inbox_comments_inbox_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='followRequests',
            field=models.ManyToManyField(blank=True, to='authors.followrequest'),
        ),
    ]
