# Generated by Django 4.1.2 on 2022-11-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='liked', max_length=200)),
                ('post', models.CharField(default='liked', max_length=200)),
                ('items', models.ManyToManyField(blank=True, to='post.like')),
            ],
        ),
    ]
