# Generated by Django 4.1.3 on 2022-12-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_like_object_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='postId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', max_length=200),
        ),
    ]
