# Generated by Django 4.1.2 on 2022-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_like_postid_alter_like_object_alter_like_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='post',
        ),
        migrations.AddField(
            model_name='liked',
            name='postId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
