# Generated by Django 4.1.3 on 2022-12-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
