# Generated by Django 4.1.3 on 2022-12-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_liked_post_liked_postid'),
        ('post', '0006_node_name'),
    ]

    operations = [
    ]
