# Generated by Django 4.1.3 on 2022-12-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_single_author_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', max_length=25)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='authors.single_author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='authors.single_author')),
            ],
        ),
    ]
