# Generated by Django 4.1.3 on 2022-12-04 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_single_author_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_username', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalAuthors', to='authors.single_author')),
            ],
        ),
    ]
