# Generated by Django 4.1.3 on 2022-12-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_externalfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalfollowers',
            name='groupNumber',
            field=models.IntegerField(default=0),
        ),
    ]
