# Generated by Django 4.1.3 on 2022-12-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_followrequest'),
        ('authors', '0004_externalfollowers_groupnumber'),
    ]

    operations = [
    ]
