# Generated by Django 4.1.3 on 2022-12-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('api', models.CharField(max_length=255)),
                ('authorization', models.CharField(max_length=255)),
            ],
        ),
    ]
