# Generated by Django 4.1 on 2022-10-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plaintext'), ('text/markdown', 'Markdown'), ('application/base64', 'app'), ('image/png;base64', 'png'), ('image/jpeg;base64', 'jpeg')], default=('text/plain', 'Plaintext'), max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='textType',
            field=models.CharField(blank=True, choices=[('text/plain', 'Plaintext'), ('text/markdown', 'Markdown')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('PRIVATE', 'Specific friend')], default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='Categories',
            field=models.CharField(default='', max_length=100),
        ),
    ]
