# Generated by Django 3.1.6 on 2022-10-22 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(6)])),
                ('uid', models.CharField(max_length=200, unique=True)),
                ('user_type', models.CharField(max_length=200)),
            ],
        ),
    ]
