# Generated by Django 3.1.6 on 2022-10-24 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='single_author',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator])),
                ('id', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(default='', max_length=255)),
                ('display_name', models.CharField(default=True, max_length=255)),
                ('url', models.URLField(default='')),
                ('github', models.URLField(default='')),
                ('profileImage', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
