# Generated by Django 3.1.6 on 2022-10-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_author',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='single_author',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='single_author',
            name='host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='single_author',
            name='id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='single_author',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='single_author',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
