# Generated by Django 4.1.3 on 2022-11-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followRequest',
        ),
    ]
