# Generated by Django 3.1.6 on 2022-10-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_single_author_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_author',
            name='confirm',
        ),
    ]
