# Generated by Django 3.1.6 on 2022-10-24 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20221024_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_author',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='authors.single_author')),
            ],
        ),
    ]
