# Generated by Django 3.1.6 on 2022-10-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20221028_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followPerson',
        ),
        migrations.AlterField(
            model_name='followers',
            name='items',
            field=models.ManyToManyField(to='authors.single_author'),
        ),
    ]
