# Generated by Django 3.1.6 on 2022-10-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20221025_0625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authors',
        ),
    ]
