# Generated by Django 4.1.2 on 2022-11-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_inbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
